---
# tasks file for docker-role
- name: push script file
  template:
    src: "install_docker.sh.j2"
    dest: "/home/{{ ansible_user }}/install_docker.sh"

- name: run the script
  command: "/bin/bash /home/{{ ansible_user }}/install_docker.sh"

- name: enable & start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: add user to group docker
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker

- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py

- name: install python-pip
  command: python2.7 /tmp/get-pip.py

- name: Install docker python
  pip: name=docker-py
